# shellcheck shell=bash
# Session name that highlights when prefix is active.
# Uses tmux conditional #{?client_prefix,...} to swap the entire segment bg.

source ~/.dotfiles/oh-my-posh/palette.sh

TMUX_POWERLINE_SEG_SESSION_PREFIX_NORMAL_BG="${TMUX_POWERLINE_SEG_SESSION_PREFIX_NORMAL_BG:-${NORD10}}"
TMUX_POWERLINE_SEG_SESSION_PREFIX_NORMAL_FG="${TMUX_POWERLINE_SEG_SESSION_PREFIX_NORMAL_FG:-${NORD6}}"
TMUX_POWERLINE_SEG_SESSION_PREFIX_HIGHLIGHT_BG="${TMUX_POWERLINE_SEG_SESSION_PREFIX_HIGHLIGHT_BG:-${NORD11}}"
TMUX_POWERLINE_SEG_SESSION_PREFIX_HIGHLIGHT_FG="${TMUX_POWERLINE_SEG_SESSION_PREFIX_HIGHLIGHT_FG:-${NORD6}}"

generate_segmentrc() {
	read -r -d '' rccontents <<EORC
export TMUX_POWERLINE_SEG_SESSION_PREFIX_NORMAL_BG="${TMUX_POWERLINE_SEG_SESSION_PREFIX_NORMAL_BG}"
export TMUX_POWERLINE_SEG_SESSION_PREFIX_NORMAL_FG="${TMUX_POWERLINE_SEG_SESSION_PREFIX_NORMAL_FG}"
export TMUX_POWERLINE_SEG_SESSION_PREFIX_HIGHLIGHT_BG="${TMUX_POWERLINE_SEG_SESSION_PREFIX_HIGHLIGHT_BG}"
export TMUX_POWERLINE_SEG_SESSION_PREFIX_HIGHLIGHT_FG="${TMUX_POWERLINE_SEG_SESSION_PREFIX_HIGHLIGHT_FG}"
EORC
	echo "$rccontents"
}

run_segment() {
	local n_bg="${TMUX_POWERLINE_SEG_SESSION_PREFIX_NORMAL_BG}"
	local n_fg="${TMUX_POWERLINE_SEG_SESSION_PREFIX_NORMAL_FG}"
	local h_bg="${TMUX_POWERLINE_SEG_SESSION_PREFIX_HIGHLIGHT_BG}"
	local h_fg="${TMUX_POWERLINE_SEG_SESSION_PREFIX_HIGHLIGHT_FG}"
	echo "#{?client_prefix,#[bg=${h_bg}]#[fg=${h_fg}],#[bg=${n_bg}]#[fg=${n_fg}]} #S "
	return 0
}
